mobile_detect.settings:
  type: config_object
  label: 'Mobile Detect'
  mapping:
    mobile_detect_is_mobile:
      type: boolean
      label: 'Add mobile_detect_is_mobile page cache context (experimental)'

condition.plugin.mobile_detect_device_type:
  type: condition.plugin
  mapping:
    devices:
      type: sequence
      sequence:
        type: string

